//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct EmailInlineObject: Codable {

    /** Email remetente */
    var remetente: String?
    /** Estrutura para reply do email enviado */
    var replyTo: String?
    /** Domínio email */
    var dominio: String?

    init(remetente: String?, replyTo: String?, dominio: String?) {
        self.remetente = remetente
        self.replyTo = replyTo
        self.dominio = dominio
    }


}

