//
// InlineResponseDefault.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct InlineResponseDefault: Codable {

    var mensagem: String?
    var tipo: String?

    init(mensagem: String?, tipo: String?) {
        self.mensagem = mensagem
        self.tipo = tipo
    }


}

