//
// CreateJobRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct CreateJobRequest: Codable {

    enum DocType: String, Codable {
        case cnh = "CNH"
        case rg = "RG"
        case renda = "RENDA"
        case residencia = "RESIDENCIA"
        case crlv = "CRLV"
    }
    /** Tipo de documento para processamento. */
    var docType: DocType
    /** Uma e-mail para envio de alertas. */
    var email: String?

    init(docType: DocType, email: String?) {
        self.docType = docType
        self.email = email
    }


}

