//
// CreateJobResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct CreateJobResponse: Codable {

    /** Identificação do job - ID */
    var idJob: String?

    init(idJob: String?) {
        self.idJob = idJob
    }


}

