//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct DataExtractionInlineObject: Codable {

    var file: URL?

    init(file: URL?) {
        self.file = file
    }

    enum CodingKeys: String, CodingKey { 
        case file = "File"
    }


}

