//
// JobResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct JobResult: Codable {

    /** A URI reference that identifies the return type */
    var type: String?
    /** A short, human-readable summary of the return type */
    var title: String?
    /** The HTTP status code for this occurrence of the return */
    var status: Int?

    init(type: String?, title: String?, status: Int?) {
        self.type = type
        self.title = title
        self.status = status
    }


}

