//
// ProblemResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct ProblemResponse: Codable {

    /** A URI reference that identifies the problem type (RFC7807) */
    var type: String?
    /** A short, human-readable summary of the problem type (RFC7807) */
    var title: String?
    /** The HTTP status code for this occurrence of the problem (RFC7807) */
    var status: Int?
    /** A human-readable explanation specific to this occurrence of the problem (RFC7807) */
    var detail: String?
    /** A URI reference that identifies the specific occurrence of the problem (RFC7807) */
    var instance: String?

    init(type: String?, title: String?, status: Int?, detail: String?, instance: String?) {
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
    }


}

