//
// Processing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct Processing: Codable {

    /** Em processamento. */
    var status: String?

    init(status: String?) {
        self.status = status
    }


}

