//
// StartJob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



struct StartJob: Codable {

    /** A endereço URL (HTTPS) para notificação de conclusão de processamento. */
    var callbackAddress: String?

    init(callbackAddress: String?) {
        self.callbackAddress = callbackAddress
    }


}

