//
// RespostaResumoMensalCamaraLDL.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

struct RespostaResumoMensalCamaraLDL: Codable {

    var value: [ResumoMensalCamaraLDL]?
    var odataContext: String?

    init(value: [ResumoMensalCamaraLDL]?, odataContext: String?) {
        self.value = value
        self.odataContext = odataContext
    }

    enum CodingKeys: String, CodingKey {
        case value
        case odataContext = "@odata.context"
    }
}

