//
// RespostaResumoMensalC3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

struct RespostaResumoMensalC3: Codable {

    var value: [ResumoMensalC3]?
    var odataContext: String?

    init(value: [ResumoMensalC3]?, odataContext: String?) {
        self.value = value
        self.odataContext = odataContext
    }

    enum CodingKeys: String, CodingKey {
        case value
        case odataContext = "@odata.context"
    }
}

