//
// RespostaResumoMensalBMFDrv.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

struct RespostaResumoMensalBMFDrv: Codable {

    var value: [ResumoMensalBMFDrv]?
    var odataContext: String?

    init(value: [ResumoMensalBMFDrv]?, odataContext: String?) {
        self.value = value
        self.odataContext = odataContext
    }

    enum CodingKeys: String, CodingKey {
        case value
        case odataContext = "@odata.context"
    }
}

