//
// RespostaResumoMensalSelic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

struct RespostaResumoMensalSelic: Codable {

    var value: [ResumoMensalSelic]?
    var odataContext: String?

    init(value: [ResumoMensalSelic]?, odataContext: String?) {
        self.value = value
        self.odataContext = odataContext
    }

    enum CodingKeys: String, CodingKey {
        case value
        case odataContext = "@odata.context"
    }
}

