//
// ResumoMensalC3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Monthly summary for C3 clearinghouse */

struct ResumoMensalC3: Codable {

    /** Mês/Ano de referência no formato mmm/aaaa */
    var mes: String?
    /** Quantidade, em unidades, de cessões de crédito no período. Cessão é o instrumento jurídico pelo qual um participante (cedente) transfere a outro participante (cessionário) créditos de que é titular. Uma operação de cessão de créditos pode conter diversas parcelas de diferentes contratos de crédito. */
    var cessoes: Double?
    /** Quantidade, em milhares, de contratos cedidos no período. Contrato é o instrumento jurídico que formaliza a operação de crédito entre participantes e seus clientes. */
    var contratos: Double?
    /** Quantidade, em milhares, de parcelas que compõem os contratos cedidos no período. Parcelas são as frações de um contrato de crédito. */
    var parcelas: Double?
    /** Soma dos valores liquidados das operações de cessão de créditos realizadas no período. Valor em R$ milhões. */
    var liquidacao: Double?

    init(mes: String?, cessoes: Double?, contratos: Double?, parcelas: Double?, liquidacao: Double?) {
        self.mes = mes
        self.cessoes = cessoes
        self.contratos = contratos
        self.parcelas = parcelas
        self.liquidacao = liquidacao
    }
}

