//
// ResumoMensalBMFDrv.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

struct ResumoMensalBMFDrv: Codable {

    /** Mês/Ano de referência no formato mmm/aaaa */
    var mes: String?
    /** Liquidação Bruta sem Contraparte Central - Média diária do valor das operações no período. Calculada como a soma dos valores das obrigações do mês, dividida pelo número de dias em que ocorreram operações. Valor em R$ milhões. */
    var valorbruto: Double?
    /** Liquidação Bruta sem Contraparte Central - Média diária da quantidade de operações no período. Calculada como a soma da quantidade de operações do mês, dividida pelo número de dias em que ocorreram operações. */
    var qtdbruto: Double?
    /** Liquidação Multilateral com Contraparte Central - Média diária do valor das operações no período. Calculada como a soma dos valores das obrigações do mês, dividida pelo número de dias em que ocorreram operações. Valor em R$ milhões. */
    var valorOperacoes: Double?
    /** Liquidação Multilateral com Contraparte Central - Média diária da quantidade de operações no período. Calculada como a soma da quantidade de operações do mês, dividida pelo número de dias em que ocorreram operações. */
    var qtdOperacoes: Double?
    /** Liquidação Multilateral com Contraparte Central - Média diária dos valores efetivamente pagos em virtude das compensações oriundas da liquidação pelo saldo líquido multilateral. Calculada como a soma dos valores pagos pelos participantes devedores (ou recebidos pelos participantes credores) no mês, dividida pelo número de dias em que houve liquidação financeira. Valor em R$ milhões. */
    var liquidacao: Double?
    /** Liquidação Multilateral com Contraparte Central - Percentual do valor das operações que foi liquidado por compensação. Calculado como 1 - liquidação / valor das operações. */
    var poderCompensacao: Double?

    init(mes: String?, valorbruto: Double?, qtdbruto: Double?, valorOperacoes: Double?, qtdOperacoes: Double?, liquidacao: Double?, poderCompensacao: Double?) {
        self.mes = mes
        self.valorbruto = valorbruto
        self.qtdbruto = qtdbruto
        self.valorOperacoes = valorOperacoes
        self.qtdOperacoes = qtdOperacoes
        self.liquidacao = liquidacao
        self.poderCompensacao = poderCompensacao
    }
}

