//
// ResumoMensalSelic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Tipo usado no conjunto SELIC. */

struct ResumoMensalSelic: Codable {

    /** Mês/Ano de referência no formato mmm/aaaa */
    var mes: String?
    /** Média diária do valor das operações no período. Calculada como a soma dos valores das operações do mês, dividida pelo número de dias em que ocorreram operações. Valor em R$ milhões. */
    var valorOperacoes: Double?
    /** Média diária da quantidade de operações no período. Calculada como a soma da quantidade de operações do mês, dividida pelo número de dias em que ocorreram operações. */
    var quantidadeOperacoes: Double?

    init(mes: String?, valorOperacoes: Double?, quantidadeOperacoes: Double?) {
        self.mes = mes
        self.valorOperacoes = valorOperacoes
        self.quantidadeOperacoes = quantidadeOperacoes
    }
}

