//
// DomnioAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire

class DomainAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    class func dominioBancoGet(completion: @escaping ((_ data: BankDomainResponse?,_ error: Error?) -> Void)) {
        dominioBancoGetWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion(response?.body, error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     - GET /dominio/Banco
     - API Key:
       - type: apiKey X-Api-Key 
       - name: GatewayAPIKey
     - returns: RequestBuilder<Void> 
     */
    class func dominioBancoGetWithRequestBuilder() -> RequestBuilder<BankDomainResponse> {
        let path = "/dominio/Banco"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<BankDomainResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    class func dominioCBOGet(completion: @escaping ((_ data: CBODomainResponse?,_ error: Error?) -> Void)) {
        dominioCBOGetWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion(response?.body, error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     - GET /dominio/CBO
     - API Key:
       - type: apiKey X-Api-Key 
       - name: GatewayAPIKey
     - returns: RequestBuilder<Void> 
     */
    class func dominioCBOGetWithRequestBuilder() -> RequestBuilder<CBODomainResponse> {
        let path = "/dominio/CBO"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CBODomainResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
