//
// TimelineAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire

class TimelineAPI {
    /**

     - parameter numeroProposta: (query)  (optional)
     - parameter cnpj: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    class func timelineGet(numeroProposta: String? = nil, cnpj: String? = nil, completion: @escaping ((_ data: TimelineResponse?,_ error: Error?) -> Void)) {
        timelineGetWithRequestBuilder(numeroProposta: numeroProposta, cnpj: cnpj).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - GET /timeline
     - API Key:
       - type: apiKey X-Api-Key 
       - name: GatewayAPIKey
     - parameter numeroProposta: (query)  (optional)
     - parameter cnpj: (query)  (optional)
     - returns: RequestBuilder<Model4> 
     */
    class func timelineGetWithRequestBuilder(numeroProposta: String? = nil, cnpj: String? = nil) -> RequestBuilder<TimelineResponse> {
        let path = "/timeline"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "numeroProposta": numeroProposta, 
            "cnpj": cnpj
        ])
        
        let requestBuilder: RequestBuilder<TimelineResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
